// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe6_uZWAY9Dzbjo9-KInt2Z3C69wZU5es',
    appId: '1:1023459484379:web:578d81fbf7eb55a9aea2fe',
    messagingSenderId: '1023459484379',
    projectId: 'fruit-hub-600f6',
    authDomain: 'fruit-hub-600f6.firebaseapp.com',
    storageBucket: 'fruit-hub-600f6.firebasestorage.app',
    measurementId: 'G-4DXK7NL2DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFt1xbv7iutK1llX9W7Eb2xebdIzAFlT0',
    appId: '1:1023459484379:android:e481db2340745bfaaea2fe',
    messagingSenderId: '1023459484379',
    projectId: 'fruit-hub-600f6',
    storageBucket: 'fruit-hub-600f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEI7TlSPUk_rL5-PtA_F6ao9SWgPUGU1M',
    appId: '1:1023459484379:ios:444d3b0cbb05f216aea2fe',
    messagingSenderId: '1023459484379',
    projectId: 'fruit-hub-600f6',
    storageBucket: 'fruit-hub-600f6.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEI7TlSPUk_rL5-PtA_F6ao9SWgPUGU1M',
    appId: '1:1023459484379:ios:444d3b0cbb05f216aea2fe',
    messagingSenderId: '1023459484379',
    projectId: 'fruit-hub-600f6',
    storageBucket: 'fruit-hub-600f6.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe6_uZWAY9Dzbjo9-KInt2Z3C69wZU5es',
    appId: '1:1023459484379:web:909ea59cf5cb152baea2fe',
    messagingSenderId: '1023459484379',
    projectId: 'fruit-hub-600f6',
    authDomain: 'fruit-hub-600f6.firebaseapp.com',
    storageBucket: 'fruit-hub-600f6.firebasestorage.app',
    measurementId: 'G-QVGNNHE3KF',
  );
}
